// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

// Input to create or update a user
type CreateUserInput struct {
	ID   *int   `json:"id"`
	Name string `json:"name"`
}

// A single user entity
type User struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
}
